###############################################################################
# © Copyright IBM Corporation 2020, 2021
###############################################################################

###############################################################################
# This sample playbook demonstrates how to execute z/OS operator commands,
# retrieve command output and retrieve outstanding messages requiring operator
# action using modules included in the Red Hat Ansible Certified Content for
# IBM Z core collection.
#
# Usage:
#  ansible-playbook -i <inventory> <playbook>
#
# Example:
#  ansible-playbook -i inventories zos_operator_basics.yml
#
#  When running this playbook, review the comments on how ths sample will
#  interact with your target, ensure you have the required authority and
#  permissions such as writing the the target directories or creating data sets.
#
#  Additional facts for this playbook can be configured to override the defaults
#  by reviewing the "Fact setting" section of this playbook, for example and
#  `system_name`.
#
# Requirements:
#   IBM z/OS core collection 1.1.0 or later
#
# Configure:
#   tgt_tmp_dir - this is the USS directory on the target which will be written
#                 to for this example.
#   ctl_tmp_dir - this is the directory on the controller which will be written
#                 to for this example.
# Optional:
#   system_name - this is the system name that will be used during this example,
#                 determined by executing `uname -n` on the target.
###############################################################################

---
- name: This playbook demonstrates executution of z/OS operator commands, retrieve command output and
    retrieve outstanding messages requiring operator action.
  hosts: all
  gather_facts: false
  vars:
    tgt_tmp_dir: "/tmp"
    ctl_tmp_dir: "/tmp"
    system_name: "VS01"
    zos_operator_command: "{{ zos_operator_command_survey | default('D M=CPU') }}"
    wait_time: "{{ wait_time_s_survey | default('1') }}"
    verbose: "{{ verbose_survey | default('false') }}"
  environment: "{{ environment_vars }}"

  tasks:
    - name: Check ibm.ibm_zos_core collection version on EE
      ansible.builtin.command: ansible-galaxy collection list ibm.ibm_zos_core
      delegate_to: localhost
      run_once: true
      register: ee_collection_out
      changed_when: false

    - name: Display installed collection version
      ansible.builtin.debug:
        var: ee_collection_out.stdout_lines
      run_once: true    

    - name: Check ZOAU version on z/OS target
      ansible.builtin.command: zoaversion
      register: zos_zoau_out
      changed_when: false

    - name: Display ZOAU version on z/OS
      ansible.builtin.debug:
        msg: "{{ zos_zoau_out.stdout_lines }}"
    
    # ##########################################################################
    # Fact setting for use by this playbook
    # ##########################################################################
    - name: Detecting system name
      ansible.builtin.command: uname -n
      register: result
      changed_when: false

    - name: Setting fact `system_name` for use by this sample
      ansible.builtin.set_fact:
        system_name: "{{ result.stdout }}"

    - name: Fact `system_name` set with value
      ansible.builtin.debug:
        msg: "{{ system_name }}"

    - name: Submit z/OS operator command.
      ibm.ibm_zos_core.zos_operator:
        cmd: "{{ zos_operator_command  }}"
        wait_time: "{{ wait_time }}"
        verbose: "{{ verbose }}"
      no_log: false
      register: result_zos_operator

    - name: Response from operator command.
      debug:
        msg: "{{ result_zos_operator.content }}"

    - name: Expose the output to the AAP API as an artifact
      set_stats:
        data:
          # This key will appear in the job's API response under "artifacts"
          agent_inline_output: "{{ result_zos_operator.content | default('No command output returned') }}"
