###############################################################################
# © Copyright IBM Corporation 2025
###############################################################################

- hosts: all
  gather_facts: false
  environment: "{{ environment_vars }}"
  vars:

    # IBM Concert variables
    concert_hostname: 'concertforz1.fyre.ibm.com:12443'
    concert_instance_id: '0000-0000-0000-0000'
    concert_api_key: "{{ vault_concert_api_key }}"
    concert_api_key_type: 'C_API_KEY'

    # z/OS Variables
    IRRDBU00_jcl: IBMUSER.JCL(IRRDBU00)
    RACFCERT_dsn: IBMUSER.CERTS.RACFCERT

  tasks:
    - block:

        - name: Install required Python modules for local script execution
          ansible.builtin.pip:
            name: 
              - openpyxl
              - colorama
            state: present
          delegate_to: localhost
          
        - name: Run job to extract Certificate data from RACF into a dataset
          ibm.ibm_zos_core.zos_job_submit:
            src: "{{IRRDBU00_jcl}}"
            location: data_set
            wait_time_s: 30
          register: IRRDBU00_job_output

        - name: Download dataset with Certificate RACF data to localhost
          ibm.ibm_zos_core.zos_fetch:
            src: "{{RACFCERT_dsn}}"
            dest: "{{ playbook_dir }}/playbook_output/RACFCERT_dsn.txt"
            flat: true

        - name: Process Certificate RACF data to generate Certificate JSON data
          ansible.builtin.script: 
           cmd: RACFCerts2Concert.py  --input "{{ playbook_dir }}/playbook_output/RACFCERT_dsn.txt" --output_json "{{ playbook_dir }}/playbook_output/RACFCerts2Concert.json" --env_name "zos-wsc" --lpar "ESYSMVS1" --output_excel "{{ playbook_dir }}/playbook_output/RACFCerts2Concert.xlsx"
           executable: /usr/bin/python3
          delegate_to: localhost

        - name: Display Certificate JSON data nicely
          ansible.builtin.debug:
            msg: "{{ lookup('file', playbook_dir + '/playbook_output/RACFCerts2Concert.json') | from_json | to_nice_json }}"
          delegate_to: localhost