source_system:
  hosts:
    esysmvs1:
      ansible_host: esysmvs1.wsclab.washington.ibm.com
      ansible_port: 22
      ansible_user: concert
      ansible_password: mar08crt
      ansible_python_interpreter: /shared/IBM/aln/v3r1/ent/pyz/pyz-311/bin/python3
      PYZ: /shared/IBM/aln/v3r1/ent/pyz/pyz-311
      ZOAU: /shared/IBM/zoautil/v1r3
      environment_vars:
        LANG: C
        LIBPATH: '{{ ZOAU }}/lib:{{ PYZ }}/lib:/lib:/usr/lib:.'
        PATH: '{{ ZOAU }}/bin:{{ PYZ }}/bin:/bin:/var/bin'
        ZOAU_HOME: '{{ ZOAU }}'
        _BPXK_AUTOCVT: 'ON'
        _CEE_RUNOPTS: FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)
        _TAG_REDIR_ERR: txt
        _TAG_REDIR_IN: txt
        _TAG_REDIR_OUT: txt